const fs=require('fs'),path=require('path');
const read=n=>JSON.parse(fs.readFileSync(path.join(__dirname,n),'utf8'));
const projects=read('catalog.json'),summary=read('compilation-summary.json'),checks=read('example-results.json');
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FRET · Toy project outputs</title><style>
:root{font-family:Segoe UI,Arial,sans-serif;color:#172b3c;background:#edf1f5}body{margin:0}header{background:#112c40;color:white;padding:38px max(30px,calc((100vw - 1160px)/2))}header small{color:#9fd8dd;letter-spacing:2px}h1{font-size:36px;margin:12px 0}h2{font-size:25px}h3{font-size:17px}p,li{line-height:1.6}main{max-width:1160px;margin:26px auto;padding:0 24px}.stats{display:flex;gap:15px;flex-wrap:wrap;margin-top:24px}.stat{background:#214254;padding:15px 24px;border-radius:8px}.stat strong{font-size:29px;display:block}.intro,.project{background:white;padding:26px 30px;margin:24px 0;border-radius:12px;border:1px solid #d4dfe7}.project{scroll-margin-top:20px}.badge{display:inline-block;color:#136344;background:#e4f5eb;padding:4px 10px;border-radius:5px;font-size:12px;font-weight:700}a{color:#176681}nav{display:flex;flex-wrap:wrap;gap:9px;margin:18px 0}nav a{background:white;border:1px solid #c5d4e0;border-radius:6px;padding:9px 12px;text-decoration:none}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;border-bottom:1px solid #dde4eb;padding:10px;vertical-align:top}th{color:#426079;background:#f1f5f8}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f0f4f8;padding:15px;border-radius:7px;font:13px/1.6 Consolas,monospace}code{font-family:Consolas,monospace}.req{border-top:1px solid #ccd9e3;padding:20px 0}.req>summary{cursor:pointer;font-size:16px;font-weight:650;line-height:1.5}.input{color:#183c58;font-size:15px}.semantics{border-left:4px solid #6b93a5;padding:10px 17px;background:#f7fafb;line-height:1.7;font-size:14px}.diagram{background:white;padding:16px;border:1px solid #dfe6ec;border-radius:8px;overflow:auto}.diagram img{max-width:100%;height:auto}.note{color:#796126;background:#fff6dc;padding:14px 18px;border-radius:7px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:24px}.muted{color:#5c7283;font-size:13px}.outcome{font-weight:700}.SATISFIED{color:#156944}.VIOLATED{color:#b23237}.INCOMPLETE,.NOT_TRIGGERED{color:#866509}footer{padding:24px;color:#526a7d}@media(max-width:700px){.cols{grid-template-columns:1fr}h1{font-size:27px}.project{padding:18px}table{font-size:12px}}
</style><header><small>NASA FRET 3.0 · ACTUAL COMPILER OUTPUT</small><h1>Separate toy projects, explicit meanings</h1><p>Door mechanism · Steel truss · Timed response · HTTP HEAD · Five decision workflows</p><div class="stats"><div class="stat"><strong>${summary.projects}</strong>separate FRET projects</div><div class="stat"><strong>${summary.requirements}</strong>compiled requirements</div><div class="stat"><strong>0</strong>parse errors</div><div class="stat"><strong>${checks.summary.passed}/${checks.summary.cases}</strong>expected example outcomes</div></div></header><main>
<section class="intro"><h2>What was implemented</h2><p>Each project has a FRET-importable JSON file, exact generated finite/infinite temporal formulas, FRET’s English explanation and its original semantic diagram. The output below was obtained by running the installed <code>FretSemantics.compile</code>, not by hand-writing formulas.</p><p class="note"><b>Scope:</b> these are implemented requirement specifications and executable observation checks. No physical door or truss is certified. FRET’s external simulation, realizability and model-checking solvers were not run. The 177 checks are a separate authored subset checker, with explicit expected outcomes; violated examples are intentional.</p><p><a href="all-projects.json">All FRET projects (JSON)</a> · <a href="compilation-summary.json">Compiler record</a> · <a href="example-results.json">All example results</a> · <a href="README.md">Reproduce / open in FRET</a></p>
<h3>Coverage of the earlier discussion</h3><table><tr><th>Discussion item</th><th>Delivered representation</th><th>Open boundary</th></tr><tr><td>Hinged room door / one hand / effortless / no sharp edges</td><td>8 decomposed requirements using the report’s 1011 target package</td><td>Original nine-requirement attachment absent; P0 and inspection procedure still need definition</td></tr><tr><td>2 m steel truss, 1000 kgf, 1 m and √2 m bars, &lt;2 cm</td><td>8 feasibility/selection requirements + separate vertical-only interpretation</td><td>Grid image, section and material data absent; optimization stays external</td></tr><tr><td>“Short time” request/response</td><td>Existing three-tick tutorial, edge and sustained-trigger alternatives</td><td>Physical tick duration, response meaning and load not supplied</td></tr><tr><td>HTTP HEAD experiment</td><td>No-content and optional correct Content-Length requirements</td><td>Only the existing stable-resource HTTP/1.1 experiment scope</td></tr><tr><td>Five six-level decision methods</td><td>Five separate workflow projects with observed gate counts and acceptance guard</td><td>Schedules are stipulated demonstrations, not measurements of human thinking</td></tr><tr><td>10 cellular-automaton rules / observer variants</td><td>Retained in existing MATLAB artifacts; not relabeled as new product requirements</td><td>Pixel entropy does not supply FRET behavior or acceptance evidence</td></tr></table>
<p class="muted">The missing attachments are explicitly marked “document not included” in the supplied chat ZIP. No omitted requirement list has been reconstructed as if it were original.</p></section><nav>${projects.map(p=>`<a href="#${p.id}">${esc(p.id.replaceAll('_',' '))}</a>`).join('')}</nav>`;
html+=`<section class="intro"><h2>Actual FRET desktop output</h2><p>The native app reports 61 requirements, 100% formalized. Its dashboard counts the built-in empty Default project in addition to the 10 delivered projects.</p><details><summary>Show captured FRET windows</summary><p><a href="screenshots/01-dashboard.png">Dashboard</a> · <a href="screenshots/02-project-list.png">Separate project list</a> · <a href="screenshots/03-door-requirements.png">Door requirement list</a></p><img style="max-width:100%;height:auto" src="screenshots/04-door-force-semantics.png" alt="Actual FRET window: DOOR-03 generated semantics, diagram and formula"></details></section>`;
for(const p of projects){
 html+=`<section class="project" id="${p.id}"><span class="badge">${p.requirements.length} / ${p.requirements.length} COMPILED</span><h2>${esc(p.title)}</h2><p><a href="${p.id}/fret-project.json">Import this project into FRET</a> · <a href="${p.id}/fret-output.json">Complete raw FRET output</a> · <a href="${p.id}/README.md">Signals and traceability</a></p><details><summary>Sources, assumptions and unresolved inputs</summary><div class="cols"><div><h3>Sources</h3><ul>${p.source.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div><div><h3>Assumptions / open inputs</h3><ul>${p.assumptions.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div></div><h3>Signal dictionary</h3><table>${Object.entries(p.variables).map(([k,v])=>`<tr><td><code>${esc(k)}</code></td><td>${esc(v)}</td></tr>`).join('')}</table></details>`;
 for(let i=0;i<p.requirements.length;i++){
  const r=p.requirements[i],s=r.semantics,examples=checks.results.filter(e=>e.id===r.reqid);
  html+=`<details class="req" ${i===0?'open':''}><summary>${r.reqid} — ${esc(r.fulltext)}</summary><p>${esc(r.rationale)}</p><h3>FRET-generated meaning</h3><div class="semantics">${s.description}</div><h3>FRET infinite-trace temporal formula</h3><pre>${esc(s.ftInfAUExpanded)}</pre><details><summary>Exact finite-trace formula and original semantic diagram</summary><pre>${esc(s.ftExpanded)}</pre><div class="diagram"><img src="${p.id}/${r.reqid}.svg" alt="Original FRET semantic template for ${r.reqid}"></div><p class="muted">Unmodified FRET diagram template selected by the compiler. See the meaning/formula above for the actual signal names and bound.</p></details><h3>Independent executable examples</h3><table><tr><th>Example</th><th>Observed contract result</th><th>Expected?</th></tr>${examples.map(e=>`<tr><td>${esc(e.label)}</td><td class="outcome ${e.actual}">${e.actual}</td><td>${e.ok?'✓':'MISMATCH'}</td></tr>`).join('')}</table></details>`;
 }
 html+='</section>';
}
html+=`<footer><p>Formalization: NASA FRET 3.0. Compiler SHA-256: <code>${summary.compiler_sha256}</code>.</p><p>FRET documentation: <a href="https://github.com/NASA-SW-VnV/fret">NASA source</a>. HTTP source: <a href="https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2">RFC 9110 §9.3.2</a> and <a href="https://www.rfc-editor.org/rfc/rfc9110.html#section-8.6">§8.6</a>.</p></footer></main></html>`;
fs.writeFileSync(path.join(__dirname,'index.html'),html);
console.log('Wrote standalone local report: '+path.join(__dirname,'index.html'));
